"""Create local catalog and durable job tables

Revision ID: d3d22d3b4b3d
Revises:
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "d3d22d3b4b3d"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "collections",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "jobs",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("state", sa.String(), nullable=False),
        sa.Column("outcome", sa.String(), nullable=True),
        sa.Column("generation", sa.Integer(), nullable=False),
        sa.Column("request", sa.JSON(), nullable=False),
        sa.Column("result", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.Column("updated_at", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_jobs_state"), "jobs", ["state"], unique=False)
    op.create_table(
        "plans",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("request", sa.JSON(), nullable=False),
        sa.Column("profile", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "recordings",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("identity_key", sa.String(), nullable=False),
        sa.Column("artist", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("version", sa.String(), nullable=False),
        sa.Column("evidence", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_recordings_identity_key"), "recordings", ["identity_key"], unique=True)
    op.create_table(
        "assets",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("recording_id", sa.String(), nullable=False),
        sa.Column("provenance", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["recording_id"],
            ["recordings.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_assets_recording_id"), "assets", ["recording_id"], unique=False)
    op.create_table(
        "events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("job_id", sa.String(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_events_job_id"), "events", ["job_id"], unique=False)
    op.create_table(
        "job_items",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("job_id", sa.String(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("state", sa.String(), nullable=False),
        sa.Column("request", sa.JSON(), nullable=False),
        sa.Column("result", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_job_items_job_id"), "job_items", ["job_id"], unique=False)
    op.create_table(
        "submissions",
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("request_hash", sa.String(), nullable=False),
        sa.Column("job_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.id"],
        ),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "asset_revisions",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("asset_id", sa.String(), nullable=False),
        sa.Column("sha256", sa.String(), nullable=False),
        sa.Column("properties", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_asset_revisions_asset_id"), "asset_revisions", ["asset_id"], unique=False
    )
    op.create_index(op.f("ix_asset_revisions_sha256"), "asset_revisions", ["sha256"], unique=True)
    op.create_table(
        "operations",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("item_id", sa.String(), nullable=False),
        sa.Column("phase", sa.String(), nullable=False),
        sa.Column("detail", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["job_items.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_operations_item_id"), "operations", ["item_id"], unique=False)
    op.create_table(
        "reviews",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("item_id", sa.String(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("state", sa.String(), nullable=False),
        sa.Column("reason", sa.String(), nullable=False),
        sa.Column("evidence", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["job_items.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_reviews_item_id"), "reviews", ["item_id"], unique=False)
    op.create_table(
        "file_locations",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("revision_id", sa.String(), nullable=False),
        sa.Column("path", sa.String(), nullable=False),
        sa.Column("managed", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["revision_id"],
            ["asset_revisions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("path"),
    )
    op.create_index(
        op.f("ix_file_locations_revision_id"), "file_locations", ["revision_id"], unique=False
    )
    op.create_table(
        "memberships",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("collection_id", sa.String(), nullable=False),
        sa.Column("recording_id", sa.String(), nullable=False),
        sa.Column("revision_id", sa.String(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["collection_id"],
            ["collections.id"],
        ),
        sa.ForeignKeyConstraint(
            ["recording_id"],
            ["recordings.id"],
        ),
        sa.ForeignKeyConstraint(
            ["revision_id"],
            ["asset_revisions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("collection_id", "recording_id"),
    )
    op.create_index(
        op.f("ix_memberships_collection_id"), "memberships", ["collection_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_memberships_collection_id"), table_name="memberships")
    op.drop_table("memberships")
    op.drop_index(op.f("ix_file_locations_revision_id"), table_name="file_locations")
    op.drop_table("file_locations")
    op.drop_index(op.f("ix_reviews_item_id"), table_name="reviews")
    op.drop_table("reviews")
    op.drop_index(op.f("ix_operations_item_id"), table_name="operations")
    op.drop_table("operations")
    op.drop_index(op.f("ix_asset_revisions_sha256"), table_name="asset_revisions")
    op.drop_index(op.f("ix_asset_revisions_asset_id"), table_name="asset_revisions")
    op.drop_table("asset_revisions")
    op.drop_table("submissions")
    op.drop_index(op.f("ix_job_items_job_id"), table_name="job_items")
    op.drop_table("job_items")
    op.drop_index(op.f("ix_events_job_id"), table_name="events")
    op.drop_table("events")
    op.drop_index(op.f("ix_assets_recording_id"), table_name="assets")
    op.drop_table("assets")
    op.drop_index(op.f("ix_recordings_identity_key"), table_name="recordings")
    op.drop_table("recordings")
    op.drop_table("plans")
    op.drop_index(op.f("ix_jobs_state"), table_name="jobs")
    op.drop_table("jobs")
    op.drop_table("collections")
    # ### end Alembic commands ###
